### ISSUE TITLE
Copy paste content from MS office missing table cell

### ISSUE THREAD

**Issue by arunjoshtech** [SyncfusionExamples/ej2-angular-7-rich-text-editor#2]
Dear sir,
I have attached source MS office document and Richtext editor Screen shot proof for the issues we are facing.

Thrird coulumn first cell is missing if I Copy paste the content from  given ms office document using ctrl+ a, then ctrl + c and ctrl+v creating this cell missing issues.

if i select only half of the content from file and copy paste then tables are fine and not missing any.
I tried in demo of React and Vue Rich text editor too and generated same error. For your kind information.

I have attached Ms office document and screen shot image

[CT SCAN OF THORAX COVID 5(Blower).docx](https://github.com/SyncfusionExamples/ej2-angular-7-rich-text-editor/files/6386788/CT.SCAN.OF.THORAX.COVID.5.Blower.docx)
![WhatsApp Image 2021-04-28 at 00 02 01](https://user-images.githubusercontent.com/63642104/116294030-1ea54980-a7b5-11eb-86c1-080e5c8af105.jpeg)

**Comment by Indrajith-Sync** [comment]
Hi @arunjoshtech ,

Greetings from Syncfusion support,

We have validated your reported query and able to reproduce the reported issue from our end. We have considered the reported issue “**Pasting the table elments from MSword to the editor, removes the empty cells in table**” as a bug from our end. We will include the fix for the reported issue, with our **May 11th** patch release. We appreciate your patience until then.
     
You can track the status of the reported issue from the below feedback link: https://www.syncfusion.com/feedback/24788/

Regards,
Indrajith

**Comment by arunjoshtech** [comment]
Dear Mr.Indrajith,
Thanks for the reply and action plan. Expecting release as it scheduled. Thanks

**Comment by Indrajith-Sync** [comment]
Hi @arunjoshtech ,

Thanks for your patience,

We have resolved the reported issue, in the Rich Text Editor with the package version **19.1.63**. 

**Release notes:** https://ej2.syncfusion.com/angular/documentation/release-notes/19.1.63/?type=all#richtexteditor 

Can you upgrade your package to this version to resolve the reported issue ?

Regards,
Indrajith

**Comment by arunjoshtech** [comment]
Dear Team,
Thanks for effort and work

**Comment by Indrajith-Sync** [comment]
Hi @arunjoshtech 

Welcome,

Please get back to us if you need any further assistance.

Regards,
Indrajith

**Comment by arunjoshtech** [comment]
Thanks for update.
