### ISSUE TITLE
Copy past from MS office to Angular is not working in Global website Demo 

### ISSUE THREAD

**Issue by arunjoshtech** [SyncfusionExamples/ej2-angular-7-rich-text-editor#6]
Dear Team,
Copy past from Attached word document is not happening in angular demo but it is working in React and Vue demo.
First I selected all exiting content in demo then deleted then tried to copy paste content  from attached MS office , and nothing happened . I have taken error code from console and attached herewith. Almost same error creating issues with our internal portable app and we have created that issues with video. kindly compare it for references

 **I did the same with React and Vue found no issues and working fine**

The same process
[MS OFFICE COPY PAST NOT HAPPENING BUT IN REACT AND VUE WORKING.docx](https://github.com/SyncfusionExamples/ej2-angular-7-rich-text-editor/files/6479519/MS.OFFICE.COPY.PAST.NOT.HAPPENING.BUT.IN.REACT.AND.VUE.WORKING.docx)
![copy past ANGULAR RICH TEXT EDITOR ERROR_WORKING FINE IN REACT AND VUE](https://user-images.githubusercontent.com/63642104/118287914-88319180-b4f1-11eb-900f-0878328f740f.png)

![error copay past  not in angular but happening in react and vue](https://user-images.githubusercontent.com/63642104/118310869-c5574d00-b50c-11eb-8ac2-c0bea10c8e76.PNG)

**Comment by arunjoshtech** [comment]
Dear Team,
**I think you have to resolve this issues in no time and This error makes Rich text editor cannot be used in web app.
Please give special emergency attention and update the package.**

**Comment by revanthKrishnan** [comment]
Hi Arunjosh,



Greetings from Syncfusion support.



We have validated your query **“In the angular demo, deleting all content and pasting the content from attached MS Word document doesn’t paste the content”.**

This issue occurred because the property **‘maxLength’** is set with a value **‘1000’**, where the pasted content has more than 1000 characters so, the paste is prevented. This can be resolved by setting the **‘maxLength’** with a larger value or removing the **‘maxLength’** property. We have prepared a sample for your reference,

**Code Snippet:**

```
<ejs-richtexteditor #toolsRTE id="alltoolRTE" [maxLength]="3000">
  . . .
</ejs-richtexteditor>
```
_**Note:** Remove the **‘maxLength’** configuration will allow the Rich Text Editor to accept infinite characters._

**Sample:** https://stackblitz.com/edit/angular-5t2qsk-xpjwdu?file=app.component.html

Please check the code snippet and the sample and let us know if it resolves the issue.

Regards,
Revanth

**Comment by arunjoshtech** [comment]
Sorry and thanks for the answer.
